                                                            In the Name of God
                                                              Hw4_Question2
                                                            Mohammadreza Arani
                                                                810100511

In [2]:
import cvxpy as cp
import numpy as np

In [41]:
# Part (a):
u1=-2
u2=-3
A=np.array([[1,-0.5],[-0.5,2]])

In [4]:
X= cp.Variable(2)


objective = cp.Minimize(   cp.quad_form(X,A) - X[0] )

constraints = [ X[0]+2*X[1] <= u1 , X[0]-4*X[1] <=u2 , 5*X[0] +76*X[1] <=1]
prob = cp.Problem(objective, constraints)
result = prob.solve()
print(X.value) # X* (Optimal Point)
print(result) # P* (Optimal Value)

[-2.33333333  0.16666667]
8.222222222222223


In [42]:
# Part (b):
S=np.array([[1 ,2], [1,-4],[5,76]])
b=np.array([[u1],[u2],[1]])
c=np.array([[-1],[0]])


X2= cp.Variable(3)


objective = cp.Maximize(   -cp.quad_form(0.5*(S.T @ X2 + cp.reshape(c,(2,))), np.linalg.inv(A)) - b.T * X2 )

constraints = [ X2 >= 0]
prob = cp.Problem(objective, constraints)
result = prob.solve()
print(X2.value) # X* (Optimal Point)
print(result) # P* (Optimal Value) == d* => String duality holds!
p_star=result


[2.83176483 2.82746724 0.03482025]
8.222222222222221


In [11]:
print("Lambda Values :")
print(X2.value)

Lambda Values :
[2.83176483 2.82746724 0.03482025]


In [33]:
# Checking KKT Conditions:
#1) primal constraints:
print(np.prod(S@X.value-b))
# 2) dual constraints:
print(-np.prod(X.value))
# 3) Complementary Slackness:
print(np.reshape(X2.value , (1,3) ) @  ( np.reshape((S@X.value.T) , (3,1) )-b ))


-0.0
0.38888888888888895
[[1.44311579e-15]]



Question 2 - Part (b):
> Indented block



In [53]:
P = np.array([[1,-0.5],[-0.5,2]])
A = np.array([[1,2],[1,-4],[5,76]])
c = np.array([[-1],[0]])

diff1 = np.reshape(np.array([-0.1,0,0.1]) , (1,3) )
diff2 = diff1





In [48]:
def  to_solve(P,A,b,c):
  X=cp.Variable(2)
  objective = cp.Minimize( cp.quad_form(X,P) +c.T@X )
  constraints = [ A@cp.reshape(X, (2,1)) <= b]
  prob = cp.Problem(objective, constraints)
  result = prob.solve()
  return result

In [55]:
p_real = np.empty(shape=(3,3))
p_real.fill(1)

p_gained = np.empty(shape=(3,3))
p_gained.fill(1)

for i in range(0,3):
  for j in range(0,3):
      b = np.reshape(np.array([ [-2 + diff1[0][i] ],[-3 +diff2[0][j]] ,[1] ]) , (3,1) )
      p_real[i][j] = to_solve(P,A,b,c)
      p_gained[i][j] = p_star - np.array([diff1[0][i] , diff2[0][j] , 0  ]) @ np.reshape(X2.value , (3,1) ) 


In [56]:
print(p_real - p_gained) # check to see the under estimator


[[2.74101269e-02 5.96012948e-02 9.62369072e-02]
 [2.01417773e-01 1.77635684e-15 4.05245013e-02]
 [4.84594256e-01 2.83176483e-01 9.52265919e-02]]


Expression(AFFINE, UNKNOWN, (2, 1))